### ISSUE TITLE
Conservation mode not "enable-able"

### ISSUE THREAD

**Issue by ActualDisaster2447** [laurento/gnome-shell-extension-ideapad#20]
Greetings, 

I'm using openSUSE Tumbleweed and have applied all of the settings in the README including `%wheel` instead of `%sudo`, but the toggle in the extension is not working. It is only able to show me if conservation mode is enabled or disabled, but nothing more. I know that the `ideapad_laptop` module is loaded for two reasons: 
1. [This](https://extensions.gnome.org/extension/4331/ideapad-mode/) extension is working and the reason why I don't want to use it is because it prompts me with a password prompt each time I want to switch Conservation Mode on and off. Yours doesn't.
2. Changing the value between 0 and 1 in `/sys/bus/platform/drivers/ideapad_acpi/VPC2004\:00/conservation_mode` enables/disables Conservation Mode respectively.

**Expected behavior:**
Extension should enable and disable Conservation Mode on-demand from GUI.

**System info**
OS: openSUSE Tumbleweed x86_64 (fully updated)
Host: 82A1 Yoga Slim 7 14IIL05
Kernel: 5.15.5-1-default
DE: GNOME 41.1
CPU: Intel i7-1065G7 (8) @ 3.900GHz
GPU: Intel Iris Plus Graphics G7
GPU: NVIDIA GeForce MX350
Memory: 3618MiB / 15731MiB

Thanks in advance!

**Comment by laurento** [comment]
Hi! :)

To test your sudo configuration, from your desktop user session (so not as root) try to run from a terminal:
`/bin/sh -c 'echo 0 | sudo tee /sys/bus/platform/drivers/ideapad_acpi/VCP2004:00/conservation_mode'`
you can use 0 or 1 to respectively disable or enable the conservation mode.

If everything is set properly, it will not prompt for password and just execute the command.

In case you get a password prompt instead, please share the content of your `/etc/sudoers.d/ideapad` file and the output of the command `groups`.

**Comment by ActualDisaster2447** [comment]
Thanks for replying so quickly!

When I execute `/bin/sh -c 'echo 0 | sudo tee /sys/bus/platform/drivers/ideapad_acpi/VCP2004:00/conservation_mode'` I get the following output:
`tee: '/sys/bus/platform/drivers/ideapad_acpi/VCP2004:00/conservation_mode': No such file or directory
0`
I checked if the file exists and it does indeed. Changing the value between `0` and `1` still works and the extension I've linked in my previous comment works (with a password prompt though). Something weird I've noticed is that your extension works without a password prompt and any errors when the _ideapad mode_ extension is enabled, however, it shows me two of those green leaves that indicate the conservation mode is on. 

Output of `sudo cat /etc/sudoers.d/ideapad` (for some reason, reading this file requires `sudo` privileges):
`%wheel ALL=(ALL) NOPASSWD: /usr/bin/tee /sys/bus/platform/drivers/ideapad_acpi/VPC????\:??/conservation_mode` 

I've also tried replacing `VPC????\:??` with `VPC2004\:00` to no avail.

Output of `groups`:
`users i2c wheel rtkit`

TIA

**Comment by laurento** [comment]
Mhhh that `No such file or directory` looks quite strange to me. When the destination file doesn't exist `tee` tries to create a new one, and in this specific case you should get a `Permission denied` instead, since you are trying to write under `/sys`.

I've just tried on one of my VMs running openSUSE Tumbleweed, and `sudo` seems to work as expected. I tried the following small example to change the disk I/O scheduler (nothing harmful, a reboot will restore the default values).

```
# add this line to the /etc/sudoers.d/ideapad file
%wheel ALL=(ALL) NOPASSWD: /usr/bin/tee /sys/block/sda/queue/scheduler

# as non-root user, run the following. It should not prompt for password
$ echo none | sudo tee /sys/block/sda/queue/scheduler
```

What you get from the command `sudo -l`?

**Comment by ActualDisaster2447** [comment]
Running `sudo -l` outputs the following:
`$ sudo -l
Matching Defaults entries for muffin on opensuse:
    always_set_home,
    secure_path=/usr/sbin\:/usr/bin\:/sbin\:/bin\:/usr/local/bin\:/usr/local/sbin,
    env_reset, env_keep="LANG LC_ADDRESS LC_CTYPE LC_COLLATE LC_IDENTIFICATION
    LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER
    LC_TELEPHONE LC_TIME LC_ALL LANGUAGE LINGUAS XDG_SESSION_COOKIE", !insults,
    targetpw

User muffin may run the following commands on opensuse:
    (ALL) ALL
    (ALL) ALL
    (ALL) NOPASSWD: ALL
    (ALL) NOPASSWD: /usr/bin/tee /sys/block/nvme0n1/queue/scheduler`

Output of the next command:
`$ echo none | sudo tee /sys/block/nvme0n1/queue/scheduler
none`

For some reason it works with this file, but with `conservation_mode`

**Comment by laurento** [comment]
I don't see the conservation_mode entry in the `sudo -l` output

**Comment by ActualDisaster2447** [comment]
It is because I thought I was supposed to replace it with the `scheduler` path to test permissions. Anyway, here is the output of `sudo -l` again:

> $ sudo -l
> Matching Defaults entries for muffin on opensuse:
>     always_set_home,
>     secure_path=/usr/sbin\:/usr/bin\:/sbin\:/bin\:/usr/local/bin\:/usr/local/sbin,
>     env_reset, env_keep="LANG LC_ADDRESS LC_CTYPE LC_COLLATE LC_IDENTIFICATION
>     LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER
>     LC_TELEPHONE LC_TIME LC_ALL LANGUAGE LINGUAS XDG_SESSION_COOKIE", !insults,
>     targetpw
> 
> User muffin may run the following commands on opensuse:
>     (ALL) ALL
>     (ALL) ALL
>     (ALL) NOPASSWD: ALL
>     (ALL) NOPASSWD: /usr/bin/tee
>         /sys/bus/platform/drivers/ideapad_acpi/VPC????\:??/conservation_mode

**Comment by laurento** [comment]
I see. Well, here is how it looks on my system (_notice the backslash in front the colon_). Moreover, next time try using "Insert code" instead of "Insert a quote" to preserve white spaces ;)

```
User xxx may run the following commands on yyy:
    (ALL : ALL) ALL
    (ALL) NOPASSWD: /usr/bin/tee
        /sys/bus/platform/drivers/ideapad_acpi/VPC????\:??/conservation_mode
```

I believe it's just a sudo configuration issue on your system. In case you made other changes to it, try cleaning it up to make it look like mine.

**Comment by ActualDisaster2447** [comment]
I've tried getting the same `sudo` configuration as you and `sudo -l` outputs the following:
```
User muffin may run the following commands on opensuse:
    (ALL) ALL
    (ALL) NOPASSWD: /usr/bin/tee
        /sys/bus/platform/drivers/ideapad_acpi/VPC2004\:00/conservation_mode
```

Now it doesn't tell me that the file doesn't exist, but it asks me for a password. I checked `/etc/sudoers.d/ideapad` and everything is fine over there. Also the module `ideapad_laptop` is loaded. I might have to change some stuff in my `sudo` config to allow this file to be used without a password, but I'll have to research that. 

```
$ /bin/sh -c 'echo 0 | sudo tee -a /sys/bus/platform/drivers/ideapad_acpi/VPC????\:??/conservation_mode'
[sudo] password for root: 
0
```

**Comment by laurento** [comment]
You should not use that `-a` param for `tee`. The command needs to fully match with the one defined in the sudo configuration, otherwise password prompt is surely expected.

`sh -c 'echo 1 | sudo tee /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode'`

**Comment by ActualDisaster2447** [comment]
Now it's working! So sorry for wasting your time on this, but turns out I'm just too used to attaching `-a` after `tee` ;) Thanks for guiding me through this and I apologize again for this mistake on my side!

**Comment by laurento** [comment]
No problem at all. You're very welcome :)

**Comment by ActualDisaster2447** [comment]
Hello again,

I just noticed today that the quirk that was happening some weeks ago is now happening again for some reason. Whenever I click on the toggle to enable or disable the conservation mode, it would just "flicker" and then close the quick settings menu without changing the state of the mode. 
I checked if executing `sh -c 'echo 1 | sudo tee /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode'` would work without `sudo` privileges and it worked. Downgrading to version 7 of the extension also seemed to solve it, although the Gnome Extensions app keeps asking to upgrade it to version 9 and eventually the extension's functionality breaks again. The problem is happening on two different machines, one running Zorin and the other running openSUSE Tumbleweed.

Merry Christmas and thanks in advance

**Comment by ActualDisaster2447** [comment]
Update: 
The fix was to replace line 82 with the following to a avoid a loop: `this._item.setToggleState(active); // Does not emit a 'toggled' signal`
This has been pointed out and explained in the issue #21. It solved my problem on both machines.

Hope you read this and wish you happy holidays!

**Comment by laurento** [comment]
Hi there! Thanks for testing #21 I couldn't replicate the issue on my machine. I'll push a new version with the fix in the coming days ;) Happy holidays!
