### ISSUE TITLE
Infinite loop when toggling the PopupSwitchMenuItem

### ISSUE THREAD

**Issue by didi-maru** [laurento/gnome-shell-extension-ideapad#21]
In Extension.js at line 82: 
```javascript
if (this._item.state != active) this._item.toggle(); // Emits a 'toggled' signal
```
A `'toggled'` signal is emitted, triggering an infinite loop where `_syncStatus` and `_setConservationMode` are called again and again.

Changing the said line to prevent emitting a `'toggled'` signal solves the issue :
```javascript
this._item.setToggleState(active); // Does not emit a 'toggled' signal
```

**Comment by laurento** [comment]
Thanks for reporting :) The issue seems to be confirmed, even though I didn't experience it on my machine. I'll release a new version with the fix in the coming days.
