### ISSUE TITLE
Syntax error when following the readme.md

### ISSUE THREAD

**Issue by agoogleuser** [laurento/gnome-shell-extension-ideapad#25]
For the line 
```bash
%wheel ALL=(ALL) NOPASSWD: /usr/bin/tee /sys/bus/platform/drivers/ideapad_acpi/VPC????\:??/conservation_mode
```
It returns
```bash
bash: syntax error near unexpected token `('
```
I'm on Fedora 35 stable up to date.

**Comment by laurento** [comment]
Hi @agoogleuser what are you doing exactly when you get this error message?

**Comment by agoogleuser** [comment]
I copy the line from readme.md and paste it in the terminal, then press enter.

**Comment by laurento** [comment]
I see. Well, that string is not actually a command, but part of the sudo configuration file that needs to be added to the existing one.

In case you're looking for the copy-n-paste version of what you need, check later in the readme.md file the section **To summarize and for easy reference...**

**Comment by agoogleuser** [comment]
My mistake, sorry for my misunderstanding.

**Comment by laurento** [comment]
No problem at all ;)
