### ISSUE TITLE
monitor on sysfs doesn't work

### ISSUE THREAD

**Issue by ellepdesk** [laurento/gnome-shell-extension-ideapad#26]
I found out that using a file monitor on sysfs does not work, so it might as well be removed.

A workaround would be to to call _syncState as final action in _setConservationMode, as well as on opening the menu.

This would also warn users that the desired setting could not be applied (for example when the permissions are not setup properly)

**Comment by laurento** [comment]
Interesting. Actually, it seems to work as expected on my Debian... or at least it was working last time I checked :) I'll have a look to confirm.

Meanwhile, could you please tell me which distro are you using and share the output of the command `mount | grep sysfs
`?

**Comment by ellepdesk** [comment]
Well, it turns out I'm wrong :)
I was playing around with the code and I couldn't get a watch on the remaining battery capacity to work.
But adding some logging clearly shows the callback working when I change the state.
