### ISSUE TITLE
Add support for GNOME 44

### ISSUE THREAD

**Issue by cewbdex** [laurento/gnome-shell-extension-ideapad#30]
Edited metadata and it has no label 
![obrazek](https://user-images.githubusercontent.com/9021297/231251348-39ec7d43-af85-4cc8-9a75-fb95da34267c.png)

**Comment by cewbdex** [comment]
Yes, sorry, I have been trying more of them, this one looks like this:
![obrazek](https://user-images.githubusercontent.com/9021297/231564840-2cce9eca-a1b2-40c6-8a5b-9895e22a6533.png)

**Comment by cewbdex** [comment]
@laurento could you reopen this?

**Comment by laurento** [comment]
Fixed in https://github.com/laurento/gnome-shell-extension-ideapad/commit/32fb7e9a2f60527723d10db84a2dba064f289b85
