### ISSUE TITLE
what is the command?

### ISSUE THREAD

**Issue by JuanH88** [laurento/gnome-shell-extension-ideapad#35]
Uninstalled GNOME DE recently and had forgotten about this extension, now I'm on cinnamon with battery at 59%.  That is to say, I forgot to deactivate the energy conservation mode🌚

**Comment by JuanH88** [comment]
I think I found it, there is a file called conservation_mode in the path "/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/" and it has a "1" written on it.  Should change it to 0 to disable it or are there additional steps?

**Comment by laurento** [comment]
Yep, just `echo 0 > conservation_mode` will do the trick.
